version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
#   user/pwd: guest/guest

  postgres:
    image: "postgres:13"
    container_name: 'java-postgres'
    ports:
      - "5430:5432"
    environment:
      - 'POSTGRES_DB=cbr'
      - 'POSTGRES_USER=usr'
      - 'POSTGRES_PASSWORD=pwd'
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
